output alert_csv: /var/log/snort/alert.csv timestamp,msg,src,srcport,dst,dstport,proto

alert icmp any any -> any any (msg:"ICMP Echo Request detected"; itype:8; sid:10001; rev:1;)

alert tcp any any -> 10.19.1.0/24 any (msg:"Possible FIN scan detected"; flags:F,12; threshold:type threshold, track by_src, count 10, seconds 10; sid:10002; rev:1;)

alert tcp any any -> 10.19.1.141 110 (msg:"Possible SYN flood on mail server"; flags:S,12; threshold:type threshold, track by_dst, count 100, seconds 10; sid:10003; rev:1;)

alert tcp any any -> 10.19.1.140 80 (msg:"File inclusion attack - /etc/passwd"; content:"/etc/passwd"; sid:10004; rev:1;)
