---
- name: configuration for DNS server
  hosts: server
  tasks:
    #- name: apt update
     # apt:
       #update_cache: yes
    - name: Install bind9
      package:
        name: bind9
        state: present
        
    - name: Create zones directory
      file:
        path: /etc/bind/zones
        state: directory
        mode: '0777'
        owner: root
        group: root

    - name: Create gruppnamn.example.com file
      copy:
        src: /etc/ansible/template/lab6/server_dns_config_forward.conf.j2  
        dest: /etc/bind/zones/gruppnamn.example.com
        owner: root
        group: root
        mode: '0777'  

    - name: Create rev.0.0.10 file
      copy:
        src: /etc/ansible/template/lab6/server_dns_config_reverse.conf.j2  
        dest: /etc/bind/zones/rev.0.0.10
        owner: root
        group: root
        mode: '0777'  

    - name: Change /etc/bind/named_conf_local
      copy:
        src: /etc/ansible/template/lab6/server_dns_named_conf_local_template.conf.j2  
        dest: /etc/bind/named.conf.local
        owner: root
        group: root
        mode: '0777'  

    - name: Change /etc/bind/named_conf_options
      copy:
        src: /etc/ansible/template/lab6/server_dns_named_conf_options_template.conf.j2  
        dest: /etc/bind/named.conf.options
        owner: root
        group: root
        mode: '0777'  

    - name: Restart bind9 service
      service:
        name: bind9
        state: restarted
        enabled: yes
        
- name: Update resolv.conf
  hosts: my_machin
  tasks:
    - name: Add nameserver to resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^nameserver'
        line: 'nameserver 10.0.0.2'

      

